version: 2
project_name: ctlptl
builds:
- main: ./cmd/ctlptl/main.go
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  env:
    - CGO_ENABLED=0
  # https://goreleaser.com/deprecations/#builds-for-windowsarm64
  ignore:
  - goos: windows
    goarch: arm64
archives:
- name_template: >-
    {{ .ProjectName }}.{{ .Version }}.
    {{- if eq .Os "darwin"}}mac
    {{- else }}{{ .Os }}{{ end }}.
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs?:'
    - '^tests?:'
    - '^cleanup:'
    - '^circleci:'
    - '^ci:'

brews:
- repository:
    owner: tilt-dev
    name: homebrew-tap
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  url_template: "https://github.com/tilt-dev/ctlptl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: "https://ctlptl.dev/"
  description: "Making local Kubernetes clusters easy to set up and tear down"
  install: |
    bin.install "ctlptl"

    # Install bash completion
    output = Utils.safe_popen_read("#{bin}/ctlptl", "completion", "bash")
    (bash_completion/"ctlptl").write output

    # Install zsh completion
    output = Utils.safe_popen_read("#{bin}/ctlptl", "completion", "zsh")
    (zsh_completion/"_ctlptl").write output

    # Install fish completion
    output = Utils.safe_popen_read("#{bin}/ctlptl", "completion", "fish")
    (fish_completion/"ctlptl.fish").write output
  test: |
    system "#{bin}/ctlptl version"
scoops:
- url_template: "https://github.com/tilt-dev/ctlptl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  repository:
    owner: tilt-dev
    name: scoop-bucket
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://ctlptl.dev/"
  description: "Making local Kubernetes clusters easy to set up and tear down"
  license: Apache-2.0
dockers:
- goos: linux
  goarch: amd64
  image_templates:
    - "tiltdev/ctlptl:{{ .Tag }}-amd64"
    - "docker/tilt-ctlptl:{{ .Tag }}-amd64"
  dockerfile: hack/Dockerfile
  use: buildx
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.description={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://github.com/tilt-dev/{{ .ProjectName }}"
  - "--label=org.opencontainers.image.source=https://github.com/tilt-dev/{{ .ProjectName }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--label=org.opencontainers.image.created={{ .Timestamp }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.licenses=Apache-2.0"
- goos: linux
  goarch: arm64
  goarm: ''
  image_templates:
    - "tiltdev/ctlptl:{{ .Tag }}-arm64"
    - "docker/tilt-ctlptl:{{ .Tag }}-arm64"
  dockerfile: hack/Dockerfile
  use: buildx
  build_flag_templates:
  - "--platform=linux/arm64"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.description={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://github.com/tilt-dev/{{ .ProjectName }}"
  - "--label=org.opencontainers.image.source=https://github.com/tilt-dev/{{ .ProjectName }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--label=org.opencontainers.image.created={{ .Timestamp }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.licenses=Apache-2.0"
docker_manifests:
- name_template: tiltdev/{{ .ProjectName }}:{{ .Tag }}
  image_templates:
  - tiltdev/{{ .ProjectName }}:{{ .Tag }}-amd64
  - tiltdev/{{ .ProjectName }}:{{ .Tag }}-arm64
- name_template: tiltdev/{{ .ProjectName }}:latest
  image_templates:
  - tiltdev/{{ .ProjectName }}:{{ .Tag }}-amd64
  - tiltdev/{{ .ProjectName }}:{{ .Tag }}-arm64
- name_template: docker/tilt-{{ .ProjectName }}:{{ .Tag }}
  image_templates:
  - docker/tilt-{{ .ProjectName }}:{{ .Tag }}-amd64
  - docker/tilt-{{ .ProjectName }}:{{ .Tag }}-arm64
- name_template: docker/tilt-{{ .ProjectName }}:latest
  image_templates:
  - docker/tilt-{{ .ProjectName }}:{{ .Tag }}-amd64
  - docker/tilt-{{ .ProjectName }}:{{ .Tag }}-arm64


# Uncomment these lines if you want to experiment with other
# parts of the release process without releasing new binaries.
# release:
#  disable: true
