project_name: ctlptl
builds:
- main: ./cmd/ctlptl/main.go
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
archives:
- name_template: "{{ .ProjectName }}.{{ .Version }}.{{ .Os }}.{{ .Arch }}"
  replacements:
    windows: windows
    darwin: mac
    linux: linux
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- tap:
    owner: tilt-dev
    name: homebrew-tap
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  url_template: "http://github.com/tilt-dev/ctlptl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: "https://ctlptl.dev/"
  description: "Making local Kubernetes clusters easy to set up and tear down"
  test: |
    system "#{bin}/ctlptl version"
scoop:
  url_template: "http://github.com/tilt-dev/tilt/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: tilt-dev
    name: scoop-bucket
  commit_author:
    name: Tilt Dev
    email: hi@tilt.dev
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://ctlptl.dev/"
  description: "Making local Kubernetes clusters easy to set up and tear down"
  license: Apache-2.0
  
# Uncomment these lines if you want to experiment with other
# parts of the release process without releasing new binaries.
# release:
#  disable: true
